env:
  browser: true
  es2021: true
overrides:
  - files:
      - '**/*.ts'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  semi: error
  prettier/prettier: error
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/no-non-null-asserted-optional-chain': 'off'
  '@typescript-eslint/ban-types': 'off'
