version: "3.9"

services:
  app:
    build:
      context: .
    environment:
      - APP_PORT=3000
      - ENVIRONMENT=LOCAL
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    restart: always
    command: npm run start
    ports:
      - 3000:3000
      - 9229:9229